[project]
name = "lumintogold"
version = "0.1.0"
description = "Юзербот с развлекательными и полезными функциями."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles==24.1.0",
    "bestconfig>=1.3.6",
    "cryptg>=0.5.2",
    "google-genai[aiohttp]==1.20",
    "loguru>=0.7.3",
    "orjson>=3.11.4",
    "psutil>=7.1.3",
    "telethon>=1.42.0",
]
